# Generated by Django 6.0.7 on 2026-07-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companhia',
            fields=[
                ('cod_companhia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('cod_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('imagem', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='quarto',
            fields=[
                ('cod_quarto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidade', models.IntegerField()),
                ('imagem', models.URLField(blank=True, null=True)),
                ('cod_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='voo',
            fields=[
                ('id_voo', models.AutoField(primary_key=True, serialize=False)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data_hora_partida', models.DateTimeField()),
                ('data_hora_chegada', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ida_volta', models.BooleanField(default=False)),
                ('promocao', models.BooleanField(default=False)),
                ('imagem', models.URLField(blank=True, null=True)),
                ('cod_companhia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.companhia')),
            ],
        ),
    ]
