# Generated by Django 6.0.7 on 2026-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='capacidade',
            field=models.IntegerField(default=0),
        ),
    ]
