# Generated by Django 6.0.7 on 2026-07-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_voo_capacidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='aeroporto',
            fields=[
                ('cod_aeroporto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('cod_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='voo',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='origem',
        ),
        migrations.AddField(
            model_name='voo',
            name='cod_aeroporto_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voos_aeroporto_destino', to='usuario.aeroporto'),
        ),
        migrations.AddField(
            model_name='voo',
            name='cod_aeroporto_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voos_aeroporto_origem', to='usuario.aeroporto'),
        ),
        migrations.AddField(
            model_name='aeroporto',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cidade'),
        ),
        migrations.AddField(
            model_name='voo',
            name='cod_cid_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voos_destino', to='usuario.cidade'),
        ),
        migrations.AddField(
            model_name='voo',
            name='cod_cid_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voos_origem', to='usuario.cidade'),
        ),
    ]
