# Generated by Django 6.0.7 on 2026-07-23 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_aeroporto_cidade_remove_voo_destino_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cidade',
            new_name='cidades',
        ),
        migrations.RenameField(
            model_name='aeroporto',
            old_name='cidade',
            new_name='cod_cidade',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='cidade',
        ),
        migrations.AddField(
            model_name='hotel',
            name='cod_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.cidades'),
        ),
    ]
