# Generated by Django 6.0.7 on 2026-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_rename_cidade_cidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroporto',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='aeroporto',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
