# Generated by Django 6.0.7 on 2026-07-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_aeroporto_cep_aeroporto_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voo',
            name='imagem',
        ),
    ]
