# Generated by Django 6.0.7 on 2026-07-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_voo_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='voo',
            old_name='id_voo',
            new_name='cod_voo',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='imagem',
        ),
        migrations.CreateModel(
            name='reservaquarto',
            fields=[
                ('cod_reservaquarto', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('cod_quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.quarto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reservavoo',
            fields=[
                ('cod_reservavoo', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('cod_voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.quarto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
